---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# HEobs

<!-- badges: start -->
<!-- badges: end -->

The **`{HEobs}`** package makes it easy to process naturalized flow data and metadata from ONS stations.

## Installation

You can install HEobs from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("lhmet-ped/HEobs")
```
## Example

Metadata from ONS stations can be obtained with:

```{r, echo = FALSE}
data_link <- "https://www.dropbox.com/s/d40adhw66uwueet/VazoesNaturaisONS_D_87UHEsDirceuAssis_2018.dat?dl=1"
```

```{r example}
library(HEobs)
## basic example code
qnat_meta <- extract_metadata(NA_character_, informative = TRUE)
qnat_meta
```

The time series of daily naturalized streamflow  ...

```{r}
qnat <- import_qnat(NA_character_, complete = TRUE, add_stn = TRUE)
str(qnat)
```

## Data from [hydrobr](https://github.com/lhmet/hydrobr/tree/master/hydrobr)


```{r}
library(dplyr)
qnat_hbr <- data.table::fread('https://raw.githubusercontent.com/lhmet/hydrobr/master/hydrobr/resources/ONS_daily_flow.csv')
str(qnat_hbr)
```


